---
title: "Meditation"
description: ""
keywords: [""]
toc: false
format:
  html:
    css: styles.css
    raw-html: true 
---

# About Me

Thanks for checking! I didn’t really know what to add here, but I wasn’t able to remove this page either, so here we are. There’s plenty of information about me on the other pages anyway :)  

Here are some funny quotes:
„Mein, dein … das sind doch bürgerliche Kategorien.“  
— Das Känguru  

„Lieber fünf Mal nachgefragt als ein Mal nachgedacht.“  
— Marc-Uwe, Die Känguru-Chroniken  

"Aber Obacht", sagt das Känguru, "das liest sich positiver, als es gemeint ist. Die benutzen da immer so 'nen Kapitalistengeheimcode.  

Die Frau liest laut vor:  
"Das Känguru war bei seiner Arbeit immer unkreativ, unpünktlich, unflexibel, desinteressiert, nicht belastbar, kaum teamfähig, schwer zu begeistern und unkreativ. Vorgesetzten gegenüber war es unfähig, sich unterzuordnen, vulgär, obszön und gelegentlich handgreiflich. Vom Tacker bis zum Flachbildschirm waren alle ihm zugeteilten Arbeitsgeräte innerhalb von Stunden nicht mehr auffindbar. Schon am zweiten Arbeitstag versuchte es mit einigem Erfolg, einen Generalstreik zu organisieren. Die Firma sah sich gezwungen, nach neun Tagen eine fristlose Kündigung auszusprechen, zu diesem Zeitpunkt war das Känguru allerdings schon mehrere Tage nicht mehr an seinem Arbeitsplatz erschienen.  

Die Zustellung der Kündigung erwies sich aus diesem Grund und auch wegen der falsch angegebenen Adresse als schwierig. Auf die Einstellung der Gehaltszahlung reagierte das Känguru mit einer Klage vor dem Arbeitsgericht. Mehrfach bezeichnete es in dem darauf folgenden Prozess seine Vorgesetzten und die Gerichtsdiener als verdammte Faschisten. Auch fragte es den Richter, ob er nicht mitbekommen habe, dass sich einige Gesetze seit den 40er Jahren geändert hätten. Nach verlorenem Prozess drohte es damit, dreckige Firmengeheimnisse zu veröffentlichen. Obwohl der Firmenleitung unklar war, von welchen dreckigen Geheimnissen das Känguru sprach, wurde es sicherheitshalber wieder eingestellt und ist seitdem nie wieder am Arbeitsplatz erschienen. Teile der Belegschaft sind bis zum heutigen Tag immer noch aufmüpfig und ungehorsam."

Die Frau lässt das Zeugnis sinken.  

"Und was liest sich positiver als es gemeint ist?", fragt sie.  

"Nächster Satz", sagt das Känguru.  

Sie liest: "In den fünf Tagen, die es tatsächlich immer bei uns gearbeitet hat, hatte es allerdings durch seine Geselligkeit zur Verbesserung des Betriebsklimas beigetragen."  

"Hä?", frage ich verwundert.  

"Das ist ein Code für übertriebenen Alkoholkonsum", sagt die Frau.  

— Das Känguru
