---
title: "Meditation"
description: ""
keywords: [""]
toc: false
format:
  html:
    css: styles.css
    raw-html: true 
---

# Music

I am a classically trained pianist and started playing the piano at the age of five, with teachers including Ricardo Valle, Antje Traub and Regula Stibi. I also started improvising and composing early on, with formal training from André Desponds and Kurt Widorski. Improvisation and composition have always fascinated me even more than interpreting written music. I almost went to conservatory, but made a last-minute decision to study medicine instead...

I give concerts from time to time—you can find upcoming ones below.

I can talk for hours about music and composers I like (please stop me if I do).

I’ve always been drawn to intricate, deep, dark, melancholic and emotionally intense music. The older I get, though, the more I also learn to appreciate simplicity.

I’m naturally drawn to late-Romantic and early 20th-century composers, particularly from the Russian part of Europe: Samuil Feinberg, Alexander Scriabin, Leopold Godowsky, Sergei Prokofiev, Sergei Rachmaninoff, Nikolai Medtner, Dmitri Kabalevsky, Igor Stravinsky, Dmitri Shostakovich, Leo Ornstein, Kurt Atterberg, and Nikolai Kapustin. But also Claude Debussy, Maurice Ravel, Francis Poulenc, Franz Liszt, Enrique Granados, Isaac Albéniz and many others.

I also have a huge fascination for more modern atmospheric music, including Bill Laurance and Jon Hopkins, and particularly for progressive rock from the 1970s: Gong, Yes, CAN, Pink Floyd, Emerson, Lake & Palmer, King Crimson and plenty of others.

The more obscure, the better. I have a BIG heart for underdogs. There are so many undiscovered pearls out there. I strongly believe that the composers who get the most attention are not necessarily the best ones. There are some absolute grand masters most people (even professional musicians) have barely heard of.

My musical strength is certainly not technical prowess. What has always interested me more is how tonal language and, particularly, harmony can create entire sound landscapes. Nature and emotions are probably the most accessible sources of inspiration for my own compositions and improvisations.

Below are two short examples. One is Alexander Scriabin’s Prelude Op. 11 No. 12 in G-sharp minor. The other is a piece for cello and piano that I wrote inspired by a few lines from the Zen poet Ko Un:

I paddled with only one oar,
then I lost that too.
For the very first time, I saw myself
out on the open water.

Sometimes I also give concerts (you can find upcoming ones below). And I’ve been playing at weddings, birthdays and other events for many years. If you’re looking for a pianist, hit me up.

## Testimonial 
“Ben’s playing really brought some life to our funeral”.

{{< video images/Video1.mp4 controls="true" >}}

{{< video images/Video2.mp4 controls="true" >}}

::: {style="text-align: center;"}
*“He would be a great composer if he knew more about music.”*\
— Camille Saint-Saëns, supposedly on Debussy

*“Why is it that whenever I hear a piece of music I don’t like, it’s always by Villa-Lobos?”*\
— Igor Stravinsky

*“Franck is a modulation machine.”*\
— Claude Debussy, on César Franck
:::
